name: jaz_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.0.1+401

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  introduction_screen: ^2.1.0
  flutter_facebook_login: ^3.0.0
  firebase_auth: ^2.0.0
  http: ^0.13.0
  path_provider: ^2.0.2
  form_field_validator: ^1.0.1
  persistent_bottom_nav_bar: ^4.0.2
  google_sign_in: ^5.0.4
  firebase_core: ^1.3.0
  cloud_firestore: ^2.3.0
  toast: ^0.1.5
  graphql: 5.0.0
  connectivity: ^3.0.6
  flutter_easyloading: ^3.0.0
  global_state: ^1.0.1
  graphql_flutter_bloc: 0.7.0
  gql: ^0.13.0
  json_annotation: ^4.0.0
  flutter_bloc: ^7.0.1
  flutter_typeahead: ^3.2.0
  flutter_keyboard_visibility: ^5.0.2
  textfield_search: ^0.8.0
  flutter_rating_bar:
  lazy_load_scrollview: 1.3.0
  flutter_paytabs_bridge: ^2.1.8
  credit_card_number_validator: ^1.0.4
  country_pickers: ^2.0.0
  date_range_form_field: ^1.0.2
  html_unescape: ^2.0.0
  flutter_svg: ^0.22.0
  paged_vertical_calendar:
    path: ./paged_vertical_calendar
  image_picker: ^0.8.4
  firebase_storage: ^10.0.3
  flutter_html: ^2.1.2
  google_maps_flutter: ^2.0.8
  google_maps_cluster_manager: ^3.0.0+1
  url_launcher: ^6.0.2
  focus_detector: ^2.0.0
  photo_view: ^0.12.0
  fluttertoast: ^8.0.8
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.7
  flutter_swiper: ^1.1.6
  firebase_crashlytics: ^2.2.2
  sign_in_with_apple: ^3.2.0
  crypto: ^3.0.1
  apple_sign_in: ^0.1.0
  optimized_cached_image: ^3.0.0
  flutter_cache_manager: ^3.1.2
  native_device_orientation: ^1.0.0
  package_info_plus: ^1.3.0
  geolocator: ^8.0.0
  geocoding: ^2.0.1
  facebook_app_events: ^0.0.1
  device_info_plus: ^3.2.1
  firebase_analytics: ^9.1.1


dependency_overrides:
  platform: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  json_serializable: ^4.0.0
  artemis: ^7.1.0-beta.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/accountmenu/
    - assets/currency/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Popins-regular
      fonts:
       - asset: fonts/ProximaNova-Regular.otf
    - family: Popins-light
      fonts:
       - asset: fonts/ProximaNova-Regular.otf
    - family: Popins-medium
      fonts:
       - asset: fonts/Proxima-Nova-Extrabold.otf
    - family: Popins-semibold
      fonts:
       - asset: fonts/Poppins-SemiBold.ttf
    - family: Popins-bold
      fonts:
        - asset: fonts/Proxima Nova Bold.otf
    - family: Popins-italic
      fonts:
        - asset: fonts/Poppins-Italic.ttf


#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
